-- =============================================================
--  COOL PERFUMES — Tabla de pedidos
--  Ejecútalo UNA VEZ en: Supabase -> SQL Editor -> New query -> Run
--
--  (Este archivo es independiente de setup.sql para que no vuelvas a
--   insertar los productos de ejemplo.)
-- =============================================================

create table if not exists public.pedidos (
  id        bigint generated by default as identity primary key,
  codigo    text not null unique,          -- ej. CP-7K3A, para ubicarlo en WhatsApp
  items     jsonb not null default '[]'::jsonb,
  total     numeric not null default 0,
  cantidad  integer not null default 0,    -- unidades totales
  estado    text not null default 'pendiente'
            check (estado in ('pendiente', 'pagado', 'cancelado')),
  nota      text,
  creado_en timestamptz not null default now()
);

create index if not exists pedidos_creado_en_idx on public.pedidos (creado_en desc);
create index if not exists pedidos_estado_idx    on public.pedidos (estado);

-- ---------- Seguridad ----------
alter table public.pedidos enable row level security;

-- La tienda es anónima: cualquier visitante puede CREAR su pedido...
drop policy if exists "Crear pedido desde la tienda" on public.pedidos;
create policy "Crear pedido desde la tienda"
  on public.pedidos for insert
  to anon, authenticated
  with check (true);

-- ...pero SOLO el administrador autenticado puede verlos y gestionarlos.
-- (Importante: sin esto, cualquiera podría leer los pedidos de tus clientes.)
drop policy if exists "Ver pedidos solo admin" on public.pedidos;
create policy "Ver pedidos solo admin"
  on public.pedidos for select
  to authenticated
  using (true);

drop policy if exists "Editar pedidos solo admin" on public.pedidos;
create policy "Editar pedidos solo admin"
  on public.pedidos for update
  to authenticated
  using (true) with check (true);

drop policy if exists "Borrar pedidos solo admin" on public.pedidos;
create policy "Borrar pedidos solo admin"
  on public.pedidos for delete
  to authenticated
  using (true);
