-- =============================================================
--  COOL PERFUMES — Configuración de Supabase
--  Cómo usarlo:
--    1. Entra a tu proyecto en https://supabase.com
--    2. Menú lateral -> SQL Editor -> New query
--    3. Pega TODO este archivo y presiona "Run"
-- =============================================================

-- ---------- 1. Tabla de productos ----------
create table if not exists public.productos (
  id           bigint generated by default as identity primary key,
  nombre       text    not null,
  marca        text    not null,
  genero       text    not null default 'unisex',
  familia      text,
  notas        text,
  ml           integer not null default 100,
  precio       numeric not null default 0,
  precio_antes numeric,
  destacado    boolean not null default false,
  open_box     boolean not null default false,   -- caja abierta / tester
  agotado      boolean not null default false,   -- sin stock
  imagen       text,
  -- Ficha completa (se muestra al hacer clic en el producto)
  descripcion   text,
  concentracion text,
  notas_salida  text,
  notas_corazon text,
  notas_fondo   text,
  duracion      text,
  estela        text,
  ocasion       text,
  creado_en    timestamptz not null default now()
);

-- Si ya habías creado la tabla antes, esto agrega las columnas nuevas.
alter table public.productos add column if not exists descripcion   text;
alter table public.productos add column if not exists concentracion text;
alter table public.productos add column if not exists notas_salida  text;
alter table public.productos add column if not exists notas_corazon text;
alter table public.productos add column if not exists notas_fondo   text;
alter table public.productos add column if not exists duracion      text;
alter table public.productos add column if not exists estela        text;
alter table public.productos add column if not exists ocasion       text;
alter table public.productos add column if not exists open_box      boolean not null default false;
alter table public.productos add column if not exists agotado       boolean not null default false;
alter table public.productos add column if not exists decant_3ml    numeric;
alter table public.productos add column if not exists decant_5ml    numeric;

-- Índice para ordenar por fecha de creación
create index if not exists productos_creado_en_idx
  on public.productos (creado_en desc);

-- ---------- 2. Seguridad (RLS) ----------
-- Cualquiera puede LEER el catálogo (la tienda es pública).
-- Solo usuarios autenticados pueden crear / editar / borrar.
alter table public.productos enable row level security;

drop policy if exists "Lectura publica de productos" on public.productos;
create policy "Lectura publica de productos"
  on public.productos for select
  to anon, authenticated
  using (true);

drop policy if exists "Escritura solo autenticados" on public.productos;
create policy "Escritura solo autenticados"
  on public.productos for all
  to authenticated
  using (true)
  with check (true);

-- ---------- 3. Storage: bucket para las fotos ----------
insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do nothing;

-- Cualquiera puede ver las imágenes
drop policy if exists "Imagenes publicas" on storage.objects;
create policy "Imagenes publicas"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'productos');

-- Solo usuarios autenticados pueden subir / reemplazar / borrar
drop policy if exists "Subir imagenes autenticados" on storage.objects;
create policy "Subir imagenes autenticados"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'productos');

drop policy if exists "Actualizar imagenes autenticados" on storage.objects;
create policy "Actualizar imagenes autenticados"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'productos');

drop policy if exists "Borrar imagenes autenticados" on storage.objects;
create policy "Borrar imagenes autenticados"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'productos');

-- =============================================================
--  4. (Opcional) Catálogo inicial de ejemplo
--
--  ⚠️ NO ejecutes esta parte si ya tienes tus productos cargados:
--     volvería a insertar estos 8 perfumes de ejemplo (duplicados).
--     Si solo necesitas crear la tabla, detente antes de este bloque.
-- =============================================================
insert into public.productos
  (nombre, marca, genero, familia, notas, ml, precio, precio_antes, destacado, imagen,
   descripcion, concentracion, notas_salida, notas_corazon, notas_fondo, duracion, estela, ocasion)
values
  ('Sauvage EDP', 'Dior', 'hombre', 'Amaderado Aromático', 'Bergamota, pimienta de Sichuan, ambroxan', 100, 429, 499, true,
   'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
   'Un clásico moderno inspirado en los espacios abiertos del desierto. Arranca fresco y cítrico, y a las pocas horas se vuelve cálido y especiado. Es de esos perfumes que funcionan para todo: oficina, salidas y clima cálido.',
   'Eau de Parfum', 'Bergamota de Calabria, mandarina', 'Pimienta de Sichuan, lavanda, nuez moscada', 'Ambroxan, vainilla, haba tonka', '8 a 10 horas', 'Intensa', 'Diario y noche'),

  ('Good Girl', 'Carolina Herrera', 'mujer', 'Floral Oriental', 'Jazmín, haba tonka, cacao', 80, 459, null, true,
   'https://images.unsplash.com/photo-1595425959632-34f2822322ce?auto=format&fit=crop&w=900&q=80',
   'Dulce y elegante a la vez. Juega con el contraste entre el jazmín luminoso y un fondo goloso de cacao y haba tonka. Muy femenino y con una presencia que se nota al entrar a un lugar.',
   'Eau de Parfum', 'Almendra, café', 'Jazmín sambac, nardo', 'Haba tonka, cacao, sándalo', '8 horas', 'Intensa', 'Noche y eventos'),

  ('Bleu de Chanel EDP', 'Chanel', 'hombre', 'Amaderado Aromático', 'Cítricos, incienso, sándalo', 100, 519, null, false,
   'https://images.unsplash.com/photo-1585218334450-afcf929da36e?auto=format&fit=crop&w=900&q=80',
   'Sobrio y muy bien equilibrado. Empieza cítrico y limpio, y termina en maderas suaves con un toque de incienso. Es la opción segura cuando quieres verte formal sin exagerar.',
   'Eau de Parfum', 'Toronja, limón, menta', 'Jengibre, nuez moscada, jazmín', 'Incienso, sándalo, cedro', '8 a 10 horas', 'Moderada', 'Oficina y noche'),

  ('Libre EDP', 'Yves Saint Laurent', 'mujer', 'Floral', 'Lavanda, azahar, vainilla', 90, 479, 540, false,
   'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
   'La combinación de lavanda fresca con vainilla cálida lo hace distinto a los florales tradicionales. Tiene carácter, sin dejar de ser suave. Rinde muchísimo en la piel.',
   'Eau de Parfum', 'Mandarina, grosella negra, lavanda', 'Lavanda, azahar, jazmín', 'Vainilla de Madagascar, almizcle, cedro', '7 a 9 horas', 'Intensa', 'Diario y noche'),

  ('Eros', 'Versace', 'hombre', 'Aromático Fougère', 'Menta, manzana verde, vainilla', 100, 329, null, false,
   'https://images.unsplash.com/photo-1593487568720-92097fb460fb?auto=format&fit=crop&w=900&q=80',
   'Fresco, dulce y muy llamativo. La menta y la manzana verde del inicio dan paso a una vainilla intensa. Es un perfume joven, ideal para salir de noche.',
   'Eau de Toilette', 'Menta, manzana verde, limón', 'Haba tonka, ambroxan, geranio', 'Vainilla, cedro, vetiver, musgo de roble', '6 a 8 horas', 'Intensa', 'Noche y fiestas'),

  ('La Vie Est Belle', 'Lancôme', 'mujer', 'Floral Gourmand', 'Iris, praliné, pachulí', 100, 445, null, false,
   'https://images.unsplash.com/photo-1622618991746-fe6004db3a47?auto=format&fit=crop&w=900&q=80',
   'Uno de los más queridos y regalados. Dulce sin ser empalagoso, con el iris dándole elegancia al praliné. Perfecto si buscas algo cálido y reconocible.',
   'Eau de Parfum', 'Grosella negra, pera', 'Iris, jazmín, azahar', 'Praliné, vainilla, pachulí, haba tonka', '8 horas', 'Intensa', 'Diario y eventos'),

  ('Baccarat Rouge 540', 'Maison Francis Kurkdjian', 'unisex', 'Ambarado Floral', 'Azafrán, jazmín, ámbar gris', 70, 1290, null, true,
   'https://images.unsplash.com/photo-1543422655-ac1c6ca993ed?auto=format&fit=crop&w=900&q=80',
   'Una joya de nicho, de las fragancias más reconocidas del mundo. Dulce, amaderado y ligeramente mineral. Con dos aplicaciones basta: su rendimiento es enorme y deja rastro por donde pasas.',
   'Eau de Parfum', 'Azafrán, jazmín', 'Amberwood, ámbar gris', 'Madera de abeto, cedro', '10 a 12 horas', 'Muy intensa', 'Ocasiones especiales'),

  ('1 Million', 'Paco Rabanne', 'hombre', 'Especiado Cuero', 'Toronja, canela, cuero', 100, 359, 410, false,
   'https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=80',
   'Un éxito de ventas desde hace años. Mezcla la frescura de la toronja con canela y cuero, dando un resultado dulce y especiado. Muy potente, poco es suficiente.',
   'Eau de Toilette', 'Toronja, menta, mandarina roja', 'Canela, rosa, especias', 'Cuero, madera ámbar, pachulí', '7 a 9 horas', 'Intensa', 'Noche')
on conflict do nothing;
